### ISSUE TITLE
No Scannable Cite Format

### ISSUE THREAD

**Issue by kerim** [Juris-M/zotero-odf-scan-plugin#48] opened 2021-10-17 11:52 UTC
"Installing the RTF/ODF-Scan add-on will add a Scannable Cite export translator to the Zotero client and change the RTF Scan option to RTF/ODF Scan."

Setup:
Zotero 5.0.97-beta.49+9432cb7e7
M1 Mac running Big Sur 11.6

Problem:
This did not happen. Is there some way to install this export translator manually? (If it was in the list of official translators it would also make it possible to add to iOS...)

**Comment by adam3smith** [comment] 2021-10-17 13:08
Duplicate of https://github.com/Juris-M/zotero-odf-scan-plugin/issues/41
which also has a workaround

**Closed as completed by adam3smith** 2021-10-17 13:08 UTC
