### ISSUE TITLE
"zg:undefined" as unique item identifier after conversion

### ISSUE THREAD

**Issue by Simplenuity** [Juris-M/zotero-odf-scan-plugin#47] opened 2021-09-30 18:55 UTC
Debug ID: D1685013483

**Environment**

- Linux Lite (based on Ubuntu 18.04), Zotero 5.0.96.3 with ODF Scan 2.0.43
- Linux Lite (based on Ubuntu 16.04), Zotero 5.0.60 with RTF/ODF Scan 2.0.39*)

*) version 2.0.43 not working in Zotero 5.0.60. File can't be chosen.

**Steps to Reproduce**
- Choose in plugin interface

File type: ODF (to markers)
Input File: odt file with active citations
Choose Output File and proceed

**Expected Behavior**
New odt file shows citation markers like this:
`{ | Allen, 2015 | | |zu:0:PQ8687P5}`

**Current Behavior**
New odt file shows citation markers like this:
`{ | (Allen, 2015) | | |zg:undefined}`
i.e. all citations have "zg:undefined" as unique item identifier

**Comment by adam3smith** [comment] 2021-10-07 15:41
Is this an unsynced library? I can't replicate this locally, but all my libraries are synced, so have numerical ideas other than 0.

**Comment by Simplenuity** [comment] 2021-10-07 16:36
Yes, all three systems I've tested it on have local libraries only.

**Comment by adam3smith** [comment] 2021-10-07 16:50
Could you upload or link to a minimal .odt file with 2 citations from a local-only library here, please? It'd be a hassle for me to create that.

**Comment by Simplenuity** [comment] 2021-10-07 17:04
Please find attached two files:
* 'test (citations).odt'  -  file with active citations, some converted via plugin, others added directly
* 'test (markers).odt'  -  result of trying to convert citations in file above via plugin to markers
[test (citations).odt](https://github.com/Juris-M/zotero-odf-scan-plugin/files/7305670/test.citations.odt)
[test (markers).odt](https://github.com/Juris-M/zotero-odf-scan-plugin/files/7305671/test.markers.odt)

**Comment by Simplenuity** [comment] 2022-02-16 05:42
This is unfortunately still relevant.
Anything I can help to get this investigated or even sorted?

**Comment by nebedaay** [comment] 2022-06-24 06:38
I'm having the same issue on MacOS 12.4, LibreOffice 7.3.2.2 for Apple Silicon (M1), and Zotero 6.0.9-beta.6+b215d93ac.

My library is synced and updated with no errors. Whenever I convert a document with Zotero references to markers, all the markers have the following identifier: "zu:0:undefined."

Here are two files, the first with 2 citations I added using the regular Zotero interface, and the second with the defective plain-text citation markers generated by ODF-scan:

[Zotero reference sample (citation).odt](https://github.com/Juris-M/zotero-odf-scan-plugin/files/8973742/Zotero.reference.sample.citation.odt)
[Zotero reference sample (markers).odt](https://github.com/Juris-M/zotero-odf-scan-plugin/files/8973743/Zotero.reference.sample.markers.odt)

It would be great if someone could help me figure out what the problem is. Please let me know if I can provide any other information.

**Comment by adam3smith** [comment] 2022-06-25 01:04
@nebedaay -- could you [try this version](https://github.com/Juris-M/zotero-odf-scan-plugin/releases/download/v.2.0.45-beta/zotero-odf-scan-v2.0.44-beta.xpi)?

**Comment by nebedaay** [comment] 2022-06-25 01:13
@adam3smith - Thanks for the quick fix! I installed that, and now it functions properly. I get the following markers:

> Here is a reference { | (Brown 2007) | | |zu:649:7SR4Y7YV}, and here is another { | (Hallaq 2012) | | |zu:649:24BPN6R3}.

It then converts back into Zotero references as expected. Looks like you've solved my problem. Thanks again.

Joseph

**Comment by adam3smith** [comment] 2022-06-25 02:42
@Simplenuity your issue should now also be fixed in the latest release (2.0.46)

**Closed as completed by adam3smith** 2022-06-25 02:42 UTC

**Comment by Simplenuity** [comment] 2022-06-25 06:29
@adam3smith many thanks!
Just tested in Zotero 5.0.96.3 (Linux Lite (based on Ubuntu 18.04)) with ODF Scan 2.0.46 (automatically updated): working!
Highly appreciated!

So I haven't used the one you linked to above: zotero-odf-scan-v2.0.44-beta.xpi

FYI: Haven't used this Zotero installation for a while. So am not sure whether caused by the update. But there are now two menu entries 'ODF scan'. Both are working.

**Comment by adam3smith** [comment] 2022-06-25 12:50
Thanks for testing. Your error was different, so 2.0.46 was the first version fixing it. The  duplicate menu disappears after restarting Zotero

**Comment by Simplenuity** [comment] 2022-06-25 13:29
Thanks!
