### ISSUE TITLE
ODF plugin not showing up in Zotero

### ISSUE THREAD

**Issue by small-fork** [Juris-M/zotero-odf-scan-plugin#14] opened 2018-10-19 23:49 UTC
Hello, 

I have used this plugin many times but suddenly even though it's installed, it's not showing as an option in my Zotero. I did have to recently restore my library from a backup. That's the only thing I can think of that changed.

I'm in a huge time crunch as the speech I've been working on and is cited totally with scannable cites is tomorrow.

I'd run the tests on this a month ago when I started writing but now it's not showing. There's only the built-in RTF scan, which doesn't work with the scannable cites format.

I did try removing and re-installing as well (with quitting and restarting Zotero in between.)

I'm using Zotero 5.0.56
On a Mac running High Sierra 10.13.6 (17G65)
Firefox 62.0.3 (64-bit)

I apologize for this being so panicked and I have tried searching for a solution, but am starting to become really worried given the time crunch. Would SO appreciate any possible solution!

Many thanks

**Comment by bmcmullin** [comment] 2018-10-21 17:38
I'm having this same issue (running on linux with zotero 5.0.56, ODF scan v2.0.35 final. (Suspect the underlying issue is duplicate of #13 ) As for small-fork this is on the critical path of an urgent project, so any help greatly appreciated!

**Comment by bmcmullin** [comment] 2018-10-21 20:22
Update at [zotero.org here](https://forums.zotero.org/discussion/74226/rtf-odf-scan-broken-in-last-few-days-as-of-21-oct-2018?new=1): basically need to roll back zotero temporarily until this is fixed...

**Comment by Bobavince** [comment] 2018-10-23 16:47
Same issue for me, as new user.

**Comment by ingo-m** [comment] 2018-10-24 12:24
I have the exact same problem, both on Debian 9 with Zotero 5.0.57 and on mac OS 10.13.6 with Zotero 5.0.56.

Thanks for having a look into this.

**Comment by small-fork** [comment] 2018-10-24 15:01
Thanks for the input, everyone—I did roll back to the last Zotero version for now and was able to get it exported and scanned! Appreciate the share, @bmcmullin :D

**Comment by bmcmullin** [comment] 2018-10-24 18:36
Yay! ;-)

**Comment by Bobavince** [comment] 2018-10-24 18:46
> Thanks for the input, everyone—I did roll back to the last Zotero version for now and was able to get it exported and scanned! Appreciate the share, @bmcmullin :D

Are you talking about Zotero 4 ? Otherwise may your precise the exact version ?
Problem is, Zotero 4 can't sync anymore, which is a problem for .. just getting back my own bibliography.

**Comment by BashedCode** [comment] 2018-10-27 04:20
I experienced the same thing and rolled back to Zotero 5.0.55 with the help of the comments on the Zotero forums. 
Looks like there will be a fix available soon.

This plugin is great! Thanks for all the work you've done on it!

**Comment by andreas-paul** [comment] 2018-10-28 19:03
I experienced the same issue with the most recent version of Zotero and the plugin. Hope the fix comes soon! 

As many have said before me, thanks for the plugin and the work!

**Comment by ingo-m** [comment] 2018-11-08 19:42
Thanks for providing this plug-in, without this I would not be able to use zotero at all because of collaborators using proprietary office software (which messes up reference marks).

Pinning zotero version to 5.0.55 did the trick; this required me to change hidden preferences, as described in the [forum](https://forums.zotero.org/discussion/comment/320270#Comment_320270):


> adamsmith May 6, 2014
>
>   Can I disable checking for updates in the stand-alone version of Zotero?
>
> yes. Toggle the app.update.auto and app.update.enabled hidden preferences:
> https://www.zotero.org/support/preferences/hidden_preferences

**Comment by small-fork** [comment] 2018-11-11 19:43
Hey all! @bmcmullin  @ingo-m @BashedCode  @andreas-paul (hope I got everyone still needing info) Looks like there's been an update to make the ODF show in the tools now. I had to do the manual download and update, but it is showing now.

Here's the [comment with the info on the forum.](https://forums.zotero.org/discussion/comment/320455/)

**Comment by adam3smith** [comment] 2018-11-11 22:06
yes, this should be fixed; sorry for the long wait -- a lot of different unfortunate circumstances conspiring; I hope this won't be again (as in: if the add-on breaks in the future, I hope for a much speedier fix).

**Closed as completed by adam3smith** 2018-11-11 22:06 UTC
